<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Kickdrum</description>
   <name>i_17_facility</name>
   <tag></tag>
   <elementGuidId>59b6d68a-639b-459e-8cd4-5f60eff00e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/div/div/div[3]/fieldset/div/p4p-reservations-wizard/div/div[2]/div[1]/overview/p4p-reservation-overview-section/div[2]/div[1]/form/div[2]/div/select/option[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/div/div/div[3]/fieldset/div/p4p-reservations-wizard/div/div[2]/div[1]/overview/p4p-reservation-overview-section/div[2]/div[1]/form/div[2]/div/select/option[11]</value>
   </webElementProperties>
</WebElementEntity>
