<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>object_pay</name>
   <tag></tag>
   <elementGuidId>8358cdf7-5ade-4f1f-a95c-eff0172754d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div/div/div/div[2]/div/ng-view/section[2]/ng-form/div[3]/div[2]/div/div/fieldset/table/tbody[2]/tr[4]/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div/div/div/div[2]/div/ng-view/section[2]/ng-form/div[3]/div[2]/div/div/fieldset/table/tbody[2]/tr[4]/td[4]/a</value>
   </webElementProperties>
</WebElementEntity>
