<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CI_MesPosterior</name>
   <tag></tag>
   <elementGuidId>70e48248-54f5-4ae8-ab0a-885a4188f574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/div/div/div[3]/fieldset/div/p4p-reservations-wizard/div/div[2]/div[1]/overview/p4p-reservation-overview-section/div[2]/div[1]/form/div[3]/div/div[1]/ul/li[1]/div/table/thead/tr[1]/th[3]/button
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/div/div/div[3]/fieldset/div/p4p-reservations-wizard/div/div[2]/div[1]/overview/p4p-reservation-overview-section/div[2]/div[1]/form/div[3]/div/div[1]/ul/li[1]/div/table/thead/tr[1]/th[3]/button
</value>
   </webElementProperties>
</WebElementEntity>
