<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mes_NovCI</name>
   <tag></tag>
   <elementGuidId>9a1cf0ba-6a65-44d4-870a-8e53fef09692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;datepicker-622-8319-10&quot;]/button
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;datepicker-622-8319-10&quot;]/button
</value>
   </webElementProperties>
</WebElementEntity>
